#!/bin/bash -e
#	storage-server - Integrated remote backup solution
#	Copyright (C) 2019-2019 Johannes Bauer
#
#	This file is part of storage-server.
#
#	storage-server is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	storage-server is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with storage-server; if not, write to the Free Software
#	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#	Johannes Bauer <JohannesBauer@gmx.de>

install() {
	SRC="$1"
	DST="$2"
	PERMS="$3"
	OWNER="$4"
	rm -f "$DST"
	./makoset "$SRC" >"$DST"
	chmod "$PERMS" "$DST"
	chown "$OWNER" "$DST"
}

if [ "$1" == "ilo" ]; then
	chmod 644 config.json
	chmod 755 .
	chmod 755 ilo
	chmod 755 ilo/wsgi
	chown -R www-data:www-data ilo/wsgi
	chown -R www-data:www-data ilo/templates
	chown -R www-data:www-data ilo/docroot

	install "ilo/conf/apache2/ports.conf" "/etc/apache2/ports.conf" 644 root:root
	install "ilo/conf/apache2/conf-enabled/security.conf" "/etc/apache2/conf-enabled/security.conf" 644 root:root
	install "ilo/conf/apache2/mods-enabled/ssl.conf" "/etc/apache2/mods-enabled/ssl.conf" 644 root:root
	install "ilo/conf/apache2/sites-enabled/000-default.conf" "/etc/apache2/sites-enabled/000-default.conf" 644 root:root
	install "ilo/services/monitor_uptime.service" "/etc/systemd/monitor_uptime.service" 644 root:root

	systemctl enable monitor_uptime
	systemctl start monitor_uptime
	systemctl restart apache2
elif [ "$1" == "storage" ]; then
	echo "Not implemented."
else
	echo "$0 [ilo|storage]"
	exit 1
fi
