#!/usr/bin/python3
#	storage-server - Integrated remote backup solution
#	Copyright (C) 2019-2019 Johannes Bauer
#
#	This file is part of storage-server.
#
#	storage-server is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	storage-server is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with storage-server; if not, write to the Free Software
#	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#	Johannes Bauer <JohannesBauer@gmx.de>

import sys
import os

files = [
	"/usr/bin/rssh",
	"/usr/bin/scp",
	"/etc/passwd",
	"/etc/group",
	"/etc/hosts",
	"/etc/resolv.conf",
]
outdir = sys.argv[1]
if not os.path.isdir(outdir):
	print("Not a directory: %s" % (outdir))
	sys.exit(1)
cmd = [ "rsync", "-aR" ] + files + [ outdir ]
subprocess.check_call(cmd)
